name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (single-file, self-contained)
        run: |
          dotnet publish SmoothScrollClone.csproj -c Release -r win-x64 ^
            -p:PublishSingleFile=true ^
            -p:SelfContained=true ^
            -p:IncludeNativeLibrariesForSelfExtract=true ^
            -p:EnableCompressionInSingleFile=true

      - name: Locate artifact
        id: locate
        shell: pwsh
        run: |
          $path = Get-ChildItem -Path "**/bin/Release/net8.0-windows/win-x64/publish/SoftScroll.exe" -Recurse | Select-Object -First 1
          if (-not $path) { Write-Error "SoftScroll.exe not found" }
          echo "exe=$($path.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SoftScroll-win-x64
          path: ${{ steps.locate.outputs.exe }}

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Soft Scroll ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.locate.outputs.exe }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
